# Generated by Django 5.1 on 2024-12-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp_secret',
            field=models.CharField(default='SXPBQHKSDC7MX7RFSPKLLJ52VRRJ2TBB', max_length=16),
        ),
    ]
