# Generated by Django 5.1 on 2024-12-17 11:32

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userotp_otp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp_secret',
            field=models.CharField(blank=True, default=pyotp.random_base32, max_length=32),
        ),
    ]
