# Generated by Django 5.1 on 2025-01-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userotp_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp_secret',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
