version: '3.9'

services:
  django:
    image: artemsim/docker_ci:version_2.1
    container_name: django
    environment:
      DB_HOST: pgdb
      DB_PORT: 5432
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - pgdb

  pgdb:
    # image: postgres:${APP_DOCKER_TAG:-latest}
    image: postgres
    container_name: pgdb
    env_file: "myshop.env"
    ports:
      - 5433:5432 # первый порт локальный второй в контейнере 
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    restart: always    

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redisdata:/data
    restart : always

    
  rabbitmq:
    restart: always
    image: rabbitmq:management
    container_name: rabbitmq
    env_file: "myshop.env"
    ports: 
      - 5672:5672
      - 15672:15672

  celery: 
    restart: always
    build: .
    container_name: celery
    command: celery -A myshop worker -l info
    ports:
      - 127.0.0.1:5555:5555
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      