version: '3.9'

services:
  # django:
  #   build: . 
  #   container_name: django
  #   command: python manage.py runserver 0.0.0.0:8000
  #   volumes: 
  #     - .:/app
  #   ports:
  #     - 8000:8000
  #   depends_on:
  #     - pgdb

  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      POSTGRES_DB: myshop
      POSTGRES_USER: artem
      POSTGRES_PASSWORD: 123
    ports:
      - 5432:5432 
    volumes: 
      - ./pgdata:/var/lib/postgresql/data
    restart: always    

  redis:
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ./redisdata:/data
    restart : always

    
  rabbitmq:
    restart: always
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 123
    ports: 
      - 5672:5672
      - 15672:15672

  celery: 
    restart: always
    build: .
    container_name: celery
    command: celery -A myshop worker -l info
    ports:
      - 127.0.0.1:5555:5555
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      