name: Docker CI

# on:
#     release:
#         types: [published]

on:
    pull_request: 
        branches: ['main']


jobs: 
    docker_create:
        runs-on: ubuntu-latest 
        env:
            LOGIN: artemsim
            NAME: docker_ci
        steps:
            - uses: actions/checkout@v4

            - name: Login in docker
              run: echo artemA28.04 | docker login -u artemsim --password-stdin

            - name: Build docker compose 
              run:  docker-compose build
              
            - name: Push image to docker 
              run: docker-compose push artemsim/docker_ci


                

        