name: Docker CI

on:
    release:
        types: [published]

# on:
#     pull_request: 
#         branches: ['main']


jobs: 
    docker_create:
        runs-on: ubuntu-latest 
        
        steps:
            - uses: actions/checkout@v4

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: artemsim
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v6
              with:
                push: true
                tags: artemsim/docker_ci
                

        